apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbGJuOTB1ZS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWjNkNWJtSnNhV1ZrWkRwQmMyUTBNalE1TkRGZllRPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
